name: Build and deploy to Cloud Run (dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest

    name: Running tests before building

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Run tests
      run: |
        cd web
        npm ci
        npm run test
        npm run lint

  build-nuxt-app:
    runs-on: ubuntu-latest
    name: Build and deploy nuxt.js app to firebase hosting
    needs: tests

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build nuxt.js app
      run: |
        cd web
        npm ci
        npm run generate
    
    - name: Edit firebase deploy file
      run: |
        export channel=waik-main-dev
        node edit-firebase-config-target.js 
      
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000 }}'
        projectId: zal1000
        channelID: live
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels

  build-nuxt-container:
    runs-on: ubuntu-latest
    name: Build nuxt.js serverside app
    needs: tests

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build nuxt.js container
      run: |
        cd web
        docker build --tag gcr.io/zal1000/waik/website:$GITHUB_SHA .

    - name: Push container images to gcr.io
      run: |
        docker push gcr.io/zal1000/waik/website:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy waik-main-dev \
        --region europe-north1 \
        --image gcr.io/zal1000/waik/website:$GITHUB_SHA \
        --platform managed \
        --project zal1000

  build-api-container:
    runs-on: ubuntu-latest
    needs: tests
    name: Build api and deploy to cloud run

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000.client_email }}
        service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000 }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build
      run: |
        cd api
        docker build --tag gcr.io/zal1000/waik/website/api:$GITHUB_SHA .

    - name: Push
      run: |
        docker push gcr.io/zal1000/waik/website/api:$GITHUB_SHA

    - name: Deploy
      run: |
        gcloud run deploy waik-main-api \
        --region europe-west1 \
        --image gcr.io/zal1000/waik/website/api:$GITHUB_SHA \
        --platform managed \
        --allow-unauthenticated \
        --project zal1000