name: Build and deploy to Cloud Run (dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

      
    - name: Build
      run: |
        docker build --tag gcr.io/zal1000/waik/website:$GITHUB_SHA .

    - name: Push
      run: |
        docker push gcr.io/zal1000/waik/website:$GITHUB_SHA

    - name: Deploy
      run: |
        gcloud run deploy waik-main \
        --region europe-north1 \
        --image gcr.io/zal1000/waik/website:$GITHUB_SHA \
        --platform managed \
        --allow-unauthenticated \
        --project zal1000