name: Build and deploy to Firebase hosting (dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install packages and build app
      run: |
        cd web
        npm ci
        npm run build --if-present
        rm -r node_modules
        cd ..

#        npm run ngcc --if-present

    - name: 'Deploy to Firebase hosting'
      id: deploy-to-firebase-hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000 }}'
          projectId: zal1000
          channelID: dev
      env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
    
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        urls:  '${{ steps.deploy-to-firebase-hosting.outputs.details_url }}'
        # ... all your other inputs
    - name: Handle Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "60"
        minBestPracticesScore: "40"
        minPerformanceScore: "40"
  
#  test: 
#    runs-on: ubuntu-latest
#    needs: build
#    
#    steps:
#
#    - name: Download artifact from build job
#      uses: actions/download-artifact@v2
#      with:
#        name: build
#   
#    - name: Set up Node.js version
#      uses: actions/setup-node@v1
#      with:
#        node-version: '14.x'
#
#    - name: Chrome Setup
#      run: |
#        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#        sudo apt install ./google-chrome-stable_current_amd64.deb
#
#    - name: test
#      run: |
#        npm ci
#        npm run test --browsers=ChromeHeadless --watch=false --if-present
