name: Deploy functions to Firebase functions

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: install libraries
      run: |
        cd functions
        npm ci

    - name: install firebase
      run: npm i firebase-tools -g

    - name: deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive --only functions