name: Build and deploy to Cloud Run (dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Run tests
      run: |
        cd web
        npm ci
        npm run test
        npm run lint

    - name: Build nuxt.js container
      run: |
        cd web
        docker build --tag gcr.io/zal1000/waik/website:$GITHUB_SHA .

    - name: Build nuxt.js app
      run: |
        cd web
        npm run generate
    
    - name: Build socket.io container
      run: |
        cd ws
        docker build --tag gcr.io/zal1000/waik/website/ws:$GITHUB_SHA .

    - name: Push container images to gcr.io
      run: |
        docker push gcr.io/zal1000/waik/website:$GITHUB_SHA
        docker push gcr.io/zal1000/waik/website/ws:$GITHUB_SHA

    - name: Edit firebase deploy file
      run: |
        export channel=waik-main-dev
        node edit-firebase-config-target.js 

    - name: Deploy socket.io server to appengine
      run: |
        cd ws
        gcloud run deploy waik-main-ws-dev \
        --region europe-north1 \
        --image gcr.io/zal1000/waik/website/ws:$GITHUB_SHA \
        --platform managed \
        --allow-unauthenticated \
        --project zal1000 \
        --use-http2

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000 }}'
        projectId: zal1000
        channelID: live
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy waik-main-dev \
        --region europe-north1 \
        --image gcr.io/zal1000/waik/website:$GITHUB_SHA \
        --platform managed \
        --allow-unauthenticated \
        --project zal1000
