name: Build and deploy to Cloud Run

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install packages and build app
      run: |
        npm ci
        npm run build:ssr --if-present
        rm -r node_modules

    - name: Setup GCP Service Account
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000.client_email }}
        service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000 }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    - name: Build
      run: |
        docker build --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/waik/website/ssr:latest .

    - name: Push
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/waik/website/ssr:latest

    - name: Deploy
      run: |
        gcloud run deploy waik-main-beta \
        --region europe-west1 \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/waik/website/ssr \
        --platform managed \
        --allow-unauthenticated \
        --project ${{ secrets.GCP_PROJECT_ID }}

#  test: 
#    runs-on: ubuntu-latest
#    needs: build
#    
#    steps:
#
#    - name: Download artifact from build job
#      uses: actions/download-artifact@v2
#      with:
#        name: build-browser
#   
#    - name: Set up Node.js version
#      uses: actions/setup-node@v1
#      with:
#        node-version: '14.x'
#
#    - name: test
#      run: |
#        npm ci
#        npm run test --if-present
