name: Build and deploy to Cloud Run

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000.client_email }}
        service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000 }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

      
    - name: Build
      run: |
        cd api
        docker build --tag gcr.io/zal1000/waik/website/api:${{ env.GITHUB_SHA }} .

    - name: Push
      run: |
        docker push gcr.io/zal1000/waik/website/api:${{ env.GITHUB_SHA }}

    - name: Deploy
      run: |
        gcloud run deploy waik-main-api \
        --region europe-west1 \
        --image gcr.io/zal1000/waik/website/api:${{ env.GITHUB_SHA }} \
        --platform managed \
        --allow-unauthenticated \
        --project zal1000