name: Build and deploy to Firebase hosting

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
        rm -r node_modules

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .

  test: 
    runs-on: ubuntu-latest
    needs: build
    
    steps:

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app
   
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: test
      run: |
        npm ci
        npm run test --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Firebase hosting'
      id: deploy-to-firebase-hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAL1000 }}'
          projectId: zal1000
      env:
          FIREBASE_CLI_PREVIEWS: hostingchannels